### ISSUE TITLE
Default credentials to OpenStack environment variables

### ISSUE THREAD

**Issue by baurmatt** [syseleven/terraform-provider-metakube#2]
The provider forces me to give the following parameters:

```terraform
resource "metakube_cluster" "example_cluster" {
  spec {
    cloud {
      openstack {
        floating_ip_pool = "ext-net"
        username         = "john.doe@example.org"
        password         = "Test1234"
        tenant           = "test-tenant"
      }
    }
  }
}
```

Could we please default them like this?

`floating_ip_pool`: `ext-net` (That's what 99% of our customers will use)
`username`: `$OS_USERNAME`
`password`: `$OS_PASSWORD`
`tenant`: `$OS_TENANT_NAME`. Better would be `$OS_PROJECT_NAME` because the name "tenant" is deprecated in OpenStack. Also a parameter `project_id`, which takes precedence over `tenant(_name)`/`project(_name)`, would be great. Because this is what is included in the "OpenStack RC File v3".

**Comment by furkhat** [comment]
You can skip specifying `floating_ip_pool` and it will be set `ext-net` on the server side, that should be enough?
I set environment variable name for `tenant` field to be `OS_PROJECT_NAME` but I don't want to change the field name because that is the name used in API.

Changes: https://github.com/syseleven/terraform-provider-metakube/commit/6804320d8533f4ab463263ab2b7781014d33afba

**Comment by baurmatt** [comment]
`floating_ip_pool` -> Right, since https://github.com/syseleven/terraform-provider-metakube/commit/8d48eec6a889ad8c072c52f9c36891ea215b1d08 this should be fine! :)

> I set environment variable name for tenant field to be OS_PROJECT_NAME but I don't want to change the field name because that is the name used in API.

Yeah, this makes sense! :) This should probably be reported to Kubermatic to get them fix the API parameter name.
