### ISSUE TITLE
metakube_sshkey as Data Source

### ISSUE THREAD

**Issue by immenz** [syseleven/terraform-provider-metakube#54]
Since the ssh keys are bound to a metakube project, it is dangerous to define it as ressource in multiple metakube_cluster terraform states. 

Is it possible to provide the keys as a Data source, optionally with filter option for name/fingerprint/all?

**Comment by squ94wk** [comment]
Could you please elaborate on what the issue is?

I assume you have different TF modules for different clusters, right?
And you need the `metakube_sshkey`'s ID in each module to pass to the cluster resource.

If I understand correctly, you would manage the `metakube_sshkey` resource inside one of the cluster's modules and then in the others use a metakube_sshkey datasource, given it's implemented. Correct?

Would it work for you to manage the `metakube_sshkey` in one (separate) module with an output and use a terraform_remote_state data source to retrieve the id?
This way, all the modules with a cluster could have identical configuration.

**Comment by furkhat** [comment]
Hi thanks for issue, we have added metakube_sshkey datasource in v1.3.0.

Note that due to the fact that ssh resource knows only about public_key there is very little concern with security. But it can be more convenient to refer to one sshkey resource in different tf modules using sshkey datasource, and I assume that would be the main use case.
